export const LAST_UPDATED = "2026-03-18T20:00:00Z";

export const WEIGHT_CLASSES = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285];

export const WRESTLERS_BY_WEIGHT = {
  125: [
    { seed: 1, name: "Luke Lilledahl", school: "Penn State" },
    { seed: 2, name: "Eddie Ventresca", school: "Virginia Tech" },
    { seed: 3, name: "Nic Bouzakis", school: "Ohio State" },
    { seed: 4, name: "Sheldon Seymour", school: "Lehigh" },
    { seed: 5, name: "Troy Spratley", school: "Army" },
    { seed: 6, name: "Jore Volk", school: "Minnesota" },
    { seed: 7, name: "Nico Provo", school: "Stanford" },
    { seed: 8, name: "Dean Peterson", school: "Iowa" },
    { seed: 9, name: "Maximo Renteria", school: "Oregon State" },
    { seed: 10, name: "Marc-Anthony McGowan", school: "Princeton" },
    { seed: 11, name: "Angelo Centeno", school: "Virginia Tech" },
    { seed: 12, name: "Vincent Robinson", school: "Arizona State" },
  ],
  133: [
    { seed: 1, name: "Jax Forrest", school: "Oklahoma State" },
    { seed: 2, name: "Ben Davino", school: "Ohio State" },
    { seed: 3, name: "Marcus Blaze", school: "Penn State" },
    { seed: 4, name: "Aaron Seidel", school: "Virginia Tech" },
    { seed: 5, name: "Kyler Larkin", school: "Arizona State" },
    { seed: 6, name: "Drake Ayala", school: "Iowa" },
    { seed: 7, name: "Lucas Byrd", school: "Illinois" },
    { seed: 8, name: "Markel Baker", school: "Northern Illinois" },
    { seed: 9, name: "Dominick Serrano", school: "Northern Colorado" },
    { seed: 10, name: "Maximilian Leete", school: "American" },
    { seed: 11, name: "Pat Glory", school: "Princeton" },
    { seed: 12, name: "Joey Olivieri", school: "Pittsburgh" },
  ],
  141: [
    { seed: 1, name: "Jesse Mendez", school: "Ohio State" },
    { seed: 2, name: "Sergio Vega", school: "Oklahoma State" },
    { seed: 3, name: "Brock Hardy", school: "Nebraska" },
    { seed: 4, name: "Anthony Echemendia", school: "Iowa State" },
    { seed: 5, name: "Luke Stanich", school: "Lehigh" },
    { seed: 6, name: "Vince Cornella", school: "Cornell" },
    { seed: 7, name: "Nasir Bailey", school: "Iowa" },
    { seed: 8, name: "Vance Vombaur", school: "Minnesota" },
    { seed: 9, name: "Joey Olivieri", school: "Rutgers" },
    { seed: 10, name: "Jack Consiglio", school: "Stanford" },
    { seed: 11, name: "CJ Composto", school: "Penn" },
    { seed: 12, name: "Caleb Henson", school: "Virginia" },
  ],
  149: [
    { seed: 1, name: "Shayne Van Ness", school: "Penn State" },
    { seed: 2, name: "Jaxon Joy", school: "Cornell" },
    { seed: 3, name: "Cross Wasilewski", school: "Penn" },
    { seed: 4, name: "Collin Gaj", school: "Virginia Tech" },
    { seed: 5, name: "Koy Buesgens", school: "NC State" },
    { seed: 6, name: "Caleb Tyus", school: "Southern Illinois" },
    { seed: 7, name: "Ethan Stiles", school: "Ohio State" },
    { seed: 8, name: "Casey Swiderski", school: "Oklahoma State" },
    { seed: 9, name: "David Evans", school: "Utah Valley" },
    { seed: 10, name: "Aden Valencia", school: "Stanford" },
    { seed: 11, name: "Lachlan McNeil", school: "Michigan" },
    { seed: 12, name: "Ryder Block", school: "Iowa" },
    { seed: 15, name: "Ryder Block", school: "Iowa" },
  ],
  157: [
    { seed: 1, name: "PJ Duke", school: "Penn State" },
    { seed: 2, name: "Antrell Taylor", school: "Nebraska" },
    { seed: 3, name: "Meyer Shapiro", school: "Cornell" },
    { seed: 4, name: "Kaleb Larkin", school: "Arizona State" },
    { seed: 5, name: "Landon Robideau", school: "Oklahoma State" },
    { seed: 6, name: "Jude Swisher", school: "Penn" },
    { seed: 7, name: "Kannon Webster", school: "Illinois" },
    { seed: 8, name: "Brandon Cannon", school: "Ohio State" },
    { seed: 9, name: "Daniel Cardenas", school: "Stanford" },
    { seed: 10, name: "Logan Rozynski", school: "Lehigh" },
    { seed: 11, name: "Ty Watters", school: "West Virginia" },
    { seed: 12, name: "Vinny Zerban", school: "Iowa State" },
    { seed: 13, name: "Wyatt Henson", school: "Lock Haven" },
  ],
  165: [
    { seed: 1, name: "Mitchell Mesenbrink", school: "Penn State" },
    { seed: 2, name: "Joey Blaze", school: "Purdue" },
    { seed: 3, name: "Mikey Caliendo", school: "Iowa" },
    { seed: 4, name: "Nicco Ruiz", school: "Arizona State" },
    { seed: 5, name: "LaDarion Lockett", school: "Oklahoma State" },
    { seed: 6, name: "LJ Araujo", school: "Nebraska" },
    { seed: 7, name: "Max Brignola", school: "Lehigh" },
    { seed: 8, name: "Matty Bianchi", school: "Little Rock" },
    { seed: 9, name: "Bryce Hepner", school: "North Carolina" },
    { seed: 10, name: "Will Denny", school: "NC State" },
    { seed: 11, name: "Tyler Eischens", school: "Northwestern" },
    { seed: 12, name: "Louie Hayes", school: "Missouri" },
  ],
  174: [
    { seed: 1, name: "Levi Haines", school: "Penn State" },
    { seed: 2, name: "Simon Ruiz", school: "Cornell" },
    { seed: 3, name: "Christopher Minto", school: "Nebraska" },
    { seed: 4, name: "Carson Kharchla", school: "Ohio State" },
    { seed: 5, name: "Patrick Kennedy", school: "Iowa" },
    { seed: 6, name: "Matty Singleton", school: "NC State" },
    { seed: 7, name: "Cam Steed", school: "Missouri" },
    { seed: 8, name: "Alex Facundo", school: "Oklahoma State" },
    { seed: 9, name: "Beau Mantanona", school: "Michigan" },
    { seed: 10, name: "Myles Takats", school: "Bucknell" },
    { seed: 11, name: "Dean Hamiti", school: "Wisconsin" },
    { seed: 12, name: "Sam Schuyler", school: "Princeton" },
    { seed: 15, name: "Danny Wask", school: "Navy" },
  ],
  184: [
    { seed: 1, name: "Rocco Welsh", school: "Penn State" },
    { seed: 2, name: "Aeoden Sinclair", school: "Missouri" },
    { seed: 3, name: "Max McEnelly", school: "Minnesota" },
    { seed: 4, name: "James Conway", school: "Franklin & Marshall" },
    { seed: 5, name: "Brock Mantanona", school: "Michigan" },
    { seed: 6, name: "Eddie Neitenbach", school: "Wyoming" },
    { seed: 7, name: "Angelo Ferrari", school: "Iowa" },
    { seed: 8, name: "Silas Allred", school: "Nebraska" },
    { seed: 9, name: "Chris Moore", school: "Illinois" },
    { seed: 10, name: "Caleb Campos", school: "American" },
    { seed: 11, name: "Tanner Cook", school: "South Dakota State" },
    { seed: 12, name: "Chase Kranitz", school: "Pittsburgh" },
  ],
  197: [
    { seed: 1, name: "Josh Barr", school: "Penn State" },
    { seed: 2, name: "Rocky Elam", school: "Iowa State" },
    { seed: 3, name: "Stephen Little", school: "Little Rock" },
    { seed: 4, name: "Sonny Sasso", school: "Virginia Tech" },
    { seed: 5, name: "Joey Novak", school: "Wyoming" },
    { seed: 6, name: "Justin Rademacher", school: "Oregon State" },
    { seed: 7, name: "Cody Merrill", school: "Oklahoma State" },
    { seed: 8, name: "DJ Parker", school: "Oklahoma" },
    { seed: 9, name: "Angelo Posada", school: "Stanford" },
    { seed: 10, name: "Mac Stout", school: "Pittsburgh" },
    { seed: 11, name: "Camden McDanel", school: "Clarion" },
    { seed: 12, name: "Gabe Arnold", school: "Iowa" },
    { seed: 27, name: "Gabe Arnold", school: "Iowa" },
  ],
  285: [
    { seed: 1, name: "Yonger Bastida", school: "Iowa State" },
    { seed: 2, name: "Isaac Trumble", school: "NC State" },
    { seed: 3, name: "Taye Ghadiali", school: "Michigan" },
    { seed: 4, name: "AJ Ferrari", school: "Nebraska" },
    { seed: 5, name: "Nick Feldman", school: "Ohio State" },
    { seed: 6, name: "Nathan Taylor", school: "Lehigh" },
    { seed: 7, name: "Konner Doucet", school: "Oklahoma State" },
    { seed: 8, name: "Ben Kueter", school: "Iowa" },
    { seed: 9, name: "Cole Mirasola", school: "Penn State" },
    { seed: 10, name: "David Szuba", school: "Arizona State" },
    { seed: 11, name: "Alex Semenenko", school: "Brown" },
    { seed: 12, name: "Mason Rebuck", school: "Bloomsburg" },
  ],
};

export const PLACEMENT_POINTS = { 1: 16, 2: 12, 3: 10, 4: 9, 5: 7, 6: 6, 7: 4, 8: 3 };

export const SCHOOL_COLORS = {
  "Penn State": "#1E407C",
  "Ohio State": "#BB0000",
  "Nebraska": "#E41C38",
  "Oklahoma State": "#FF7300",
  "Iowa State": "#C8102E",
  "Iowa": "#FFCD00",
  "Virginia Tech": "#75162F",
  "Cornell": "#B31B1B",
  "Missouri": "#F1B82D",
  "Michigan": "#FFCB05",
  "Minnesota": "#7A0019",
  "NC State": "#CC0000",
  "Stanford": "#8C1515",
  "Arizona State": "#8C1D40",
  "Wyoming": "#492F24",
  "Purdue": "#CEB888",
  "Illinois": "#E84A27",
  "Northwestern": "#4E2A84",
  "Wisconsin": "#C5050C",
  "Pittsburgh": "#003594",
  "Lehigh": "#652B16",
  "Army": "#1F3764",
  "Harvard": "#A51C30",
  "Bucknell": "#E87722",
  "Northern Iowa": "#4B116F",
  "Northern Illinois": "#BA0C2F",
  "Northern Colorado": "#003366",
  "Oklahoma": "#841617",
  "Oregon State": "#D73F09",
  "Penn": "#011F5B",
  "Maryland": "#E03A3E",
  "Franklin & Marshall": "#002868",
  "Little Rock": "#75003B",
  "South Dakota State": "#00539B",
  "Clarion": "#003087",
  "Navy": "#00205B",
  "West Virginia": "#002855",
  "Air Force": "#00308F",
  "Brown": "#4E3629",
  "Bloomsburg": "#C41230",
  "Columbia": "#69B3E7",
  "Princeton": "#E77500",
  "Rutgers": "#CC0033",
  "American": "#CC0000",
  "Southern Illinois": "#720000",
  "Utah Valley": "#275D38",
  "North Carolina": "#7BAFD4",
  "Lock Haven": "#7E1032",
  "Virginia": "#232D4B",
};

export const getSchoolColor = (school) => SCHOOL_COLORS[school] || "#666";

export const SEED_ENTRIES = [
  { id: 1742000000001, name: "Wes Uhrin", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:5,name:"Kyler Larkin",school:"Arizona State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000002, name: "Steve Popovitch", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:13,name:"Wyatt Henson",school:"Lock Haven"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000003, name: "Michael Hills", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000004, name: "Jared Leidich", picks: { 125:{seed:12,name:"Vincent Robinson",school:"Arizona State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:6,name:"LJ Araujo",school:"Nebraska"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000005, name: "Sean Bayless", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:3,name:"Mikey Caliendo",school:"Iowa"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000006, name: "Annese Bayless", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:1,name:"Jax Forrest",school:"Oklahoma State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:10,name:"Caleb Campos",school:"American"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:6,name:"Nathan Taylor",school:"Lehigh"} } },
  { id: 1742000000008, name: "Derek Hillman", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:10,name:"David Szuba",school:"Arizona State"} } },
  { id: 1742000000009, name: "Jamar Henry", picks: { 125:{seed:12,name:"Vincent Robinson",school:"Arizona State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000010, name: "Brittany Yoho", picks: { 125:{seed:12,name:"Vincent Robinson",school:"Arizona State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:3,name:"Mikey Caliendo",school:"Iowa"}, 174:{seed:1,name:"Levi Haines",school:"Penn State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:5,name:"Joey Novak",school:"Wyoming"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000011, name: "Chris Thrasher", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:2,name:"Joey Blaze",school:"Purdue"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000012, name: "Joe Unger", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:4,name:"Anthony Echemendia",school:"Iowa State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:10,name:"Logan Rozynski",school:"Lehigh"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000014, name: "Brian Westfall", picks: { 125:{seed:5,name:"Troy Spratley",school:"Army"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:3,name:"Taye Ghadiali",school:"Michigan"} } },
  { id: 1742000000015, name: "Ryan Hills", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:12,name:"Gabe Arnold",school:"Iowa"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000016, name: "Robert Elchynski", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:11,name:"CJ Composto",school:"Penn"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000017, name: "Dave Klepfer", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:15,name:"Danny Wask",school:"Navy"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000018, name: "Wes Uhrin", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:5,name:"Kyler Larkin",school:"Arizona State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000019, name: "Kris Bishop", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000020, name: "AJ Buckiso", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:3,name:"Mikey Caliendo",school:"Iowa"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000021, name: "Grant Parrish", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000022, name: "Dan Spencer", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:15,name:"Ryder Block",school:"Iowa"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000023, name: "Joe Montalbano 1", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000024, name: "Joe Montalbano 2", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000026, name: "Matthew Harrington", picks: { 125:{seed:12,name:"Vincent Robinson",school:"Arizona State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:3,name:"Taye Ghadiali",school:"Michigan"} } },
  { id: 1742000000027, name: "Hunter Bresnan", picks: { 125:{seed:12,name:"Vincent Robinson",school:"Arizona State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000028, name: "Rob Whiteside", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:27,name:"Gabe Arnold",school:"Iowa"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000029, name: "James Walker", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:8,name:"DJ Parker",school:"Oklahoma"}, 285:{seed:10,name:"David Szuba",school:"Arizona State"} } },
  { id: 1742000000030, name: "Jayden Walker", picks: { 125:{seed:10,name:"Marc-Anthony McGowan",school:"Princeton"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000031, name: "Jordan Victor", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:10,name:"Myles Takats",school:"Bucknell"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000032, name: "Todd Victor", picks: { 125:{seed:5,name:"Troy Spratley",school:"Army"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:10,name:"Will Denny",school:"NC State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000033, name: "Jim Kusar", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:4,name:"Carson Kharchla",school:"Ohio State"}, 184:{seed:6,name:"Eddie Neitenbach",school:"Wyoming"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000034, name: "Jerry Kendall", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000035, name: "Kevin McElhaney", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Mesenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000036, name: "Joe DeMore", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:3,name:"Mikey Caliendo",school:"Iowa"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000037, name: "David Rose 1", picks: { 125:{seed:5,name:"Troy Spratley",school:"Army"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:6,name:"LJ Araujo",school:"Nebraska"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
];
