export const LAST_UPDATED = "2026-03-20T01:15:00Z";

export const WEIGHT_CLASSES = [125, 133, 141, 149, 157, 165, 174, 184, 197, 285];

export const WRESTLERS_BY_WEIGHT = {
  125: [
    { seed: 1, name: "Luke Lilledahl", school: "Penn State" },
    { seed: 2, name: "Eddie Ventresca", school: "Virginia Tech" },
    { seed: 3, name: "Nic Bouzakis", school: "Ohio State" },
    { seed: 4, name: "Sheldon Seymour", school: "Lehigh" },
    { seed: 5, name: "Troy Spratley", school: "Oklahoma State" },
    { seed: 6, name: "Jore Volk", school: "Minnesota" },
    { seed: 7, name: "Nico Provo", school: "Stanford" },
    { seed: 8, name: "Dean Peterson", school: "Iowa" },
    { seed: 9, name: "Maximo Renteria", school: "Oregon State" },
    { seed: 10, name: "Marc-Anthony McGowan", school: "Princeton" },
    { seed: 11, name: "Tyler Klinsky", school: "Rider" },
    { seed: 12, name: "Vincent Robinson", school: "NC State" },
    { seed: 13, name: "Stevo Poulin", school: "Iowa State" },
    { seed: 14, name: "Jacob Moran", school: "Indiana" },
    { seed: 15, name: "Koda Holeman", school: "Cal Poly" },
    { seed: 16, name: "Ezekiel Witt", school: "North Dakota State" },
    { seed: 17, name: "Jett Strickenberger", school: "West Virginia" },
    { seed: 18, name: "Spencer Moore", school: "Illinois" },
    { seed: 19, name: "Kysen Terukina", school: "North Carolina" },
    { seed: 20, name: "Diego Sotelo", school: "Michigan" },
    { seed: 21, name: "Conrad Hendriksen", school: "Oklahoma" },
    { seed: 22, name: "Davis Motyka", school: "Penn" },
    { seed: 23, name: "Nicolar Rivera", school: "Wisconsin" },
    { seed: 24, name: "Ayden Smith", school: "Rutgers" },
    { seed: 25, name: "Kael Laurdsen", school: "Nebraska" },
    { seed: 26, name: "Cooper Flynn", school: "Chattanooga" },
    { seed: 27, name: "Brady Roark", school: "South Dakota State" },
    { seed: 28, name: "Andrew Binni", school: "Navy" },
    { seed: 29, name: "Tyler Chappell", school: "Pittsburgh" },
    { seed: 30, name: "Sulayman Bah", school: "Columbia" },
    { seed: 31, name: "Desmond Pleasant", school: "Drexel" },
    { seed: 32, name: "Mack Mauger", school: "Missouri" },
    { seed: 33, name: "Jace Schafer", school: "Bloomsburg" },
  ],
  133: [
    { seed: 1, name: "Jax Forrest", school: "Oklahoma State" },
    { seed: 2, name: "Ben Davino", school: "Ohio State" },
    { seed: 3, name: "Marcus Blaze", school: "Penn State" },
    { seed: 4, name: "Aaron Seidel", school: "Virginia Tech" },
    { seed: 5, name: "Kyler Larkin", school: "Arizona State" },
    { seed: 6, name: "Drake Ayala", school: "Iowa" },
    { seed: 7, name: "Lucas Byrd", school: "Illinois" },
    { seed: 8, name: "Markel Baker", school: "Northern Illinois" },
    { seed: 9, name: "Dominick Serrano", school: "Northern Colorado" },
    { seed: 10, name: "Maximillan Leete", school: "American" },
    { seed: 11, name: "Tyler Ferrara", school: "Cornell" },
    { seed: 12, name: "Evan Mougalian", school: "Penn" },
    { seed: 13, name: "Jacob Van Dee", school: "Nebraska" },
    { seed: 14, name: "Ethan Berginc", school: "Army" },
    { seed: 15, name: "Tyler Knox", school: "Stanford" },
    { seed: 16, name: "Zan Fugitt", school: "Wisconsin" },
    { seed: 17, name: "TK Davis", school: "Gardner Webb" },
    { seed: 18, name: "Gunner Andrick", school: "West Virginia" },
    { seed: 19, name: "Gage Walker", school: "Missouri" },
    { seed: 20, name: "Julian Farber", school: "Northern Iowa" },
    { seed: 21, name: "Sean Spidle", school: "Northwestern" },
    { seed: 22, name: "Zach Redding", school: "NC State" },
    { seed: 23, name: "Braxton Brown", school: "Maryland" },
    { seed: 24, name: "Blake Boarman", school: "Purdue" },
    { seed: 25, name: "Will Betancourt", school: "Rider" },
    { seed: 26, name: "Dylan Shawver", school: "Rutgers" },
    { seed: 27, name: "Marcel Lopez", school: "Southern Illinois" },
    { seed: 28, name: "Garrett Grice", school: "Iowa State" },
    { seed: 29, name: "Luke Willochell", school: "Wyoming" },
    { seed: 30, name: "Gabe Wisenhunt", school: "Oregon State" },
    { seed: 31, name: "Gable Strickland", school: "Lock Haven" },
    { seed: 32, name: "Andrew Austin", school: "Central Michigan" },
    { seed: 33, name: "Carter Schmidt", school: "Oklahoma" },
  ],
  141: [
    { seed: 1, name: "Jesse Mendez", school: "Ohio State" },
    { seed: 2, name: "Sergio Vega", school: "Oklahoma State" },
    { seed: 3, name: "Brock Hardy", school: "Nebraska" },
    { seed: 4, name: "Anthony Echemendia", school: "Iowa State" },
    { seed: 5, name: "Luke Stanich", school: "Lehigh" },
    { seed: 6, name: "Vince Cornella", school: "Cornell" },
    { seed: 7, name: "Nasir Bailey", school: "Iowa" },
    { seed: 8, name: "Vance Vombaur", school: "Minnesota" },
    { seed: 9, name: "Joey Olivieri", school: "Rutgers" },
    { seed: 10, name: "Jack Consiglio", school: "Stanford" },
    { seed: 11, name: "CJ Composto", school: "Penn" },
    { seed: 12, name: "Luke Simcox", school: "North Carolina" },
    { seed: 13, name: "Wyatt Henson", school: "Lock Haven" },
    { seed: 14, name: "Braeden Davis", school: "Penn State" },
    { seed: 15, name: "Elijah Griffin", school: "Rider" },
    { seed: 16, name: "Ryan Jack", school: "NC State" },
    { seed: 17, name: "Caedyn Riccardi", school: "Navy" },
    { seed: 18, name: "Carter Nogle", school: "Air Force" },
    { seed: 19, name: "Haiden Drury", school: "Utah Valley" },
    { seed: 20, name: "Julian Tagg", school: "South Dakota State" },
    { seed: 21, name: "Tyler Wells", school: "Oklahoma" },
    { seed: 22, name: "Lorenzo Frezza", school: "Columbia" },
    { seed: 23, name: "Dylan Chappell", school: "Bucknell" },
    { seed: 24, name: "Nash Singleton", school: "Oregon State" },
    { seed: 25, name: "Tom Crook", school: "Virginia Tech" },
    { seed: 26, name: "Braden Basile", school: "Army" },
    { seed: 27, name: "Gable Porter", school: "Virginia" },
    { seed: 28, name: "Pierson Manville", school: "Arizona State" },
    { seed: 29, name: "Jordan Titus", school: "West Virginia" },
    { seed: 30, name: "Dario Lemus", school: "Maryland" },
    { seed: 31, name: "Billy DeKraker", school: "Northwestern" },
    { seed: 32, name: "Matthew Martino", school: "Princeton" },
    { seed: 33, name: "Aldo Hernandez", school: "Appalachian State" },
  ],
  149: [
    { seed: 1, name: "Shayne Van Ness", school: "Penn State" },
    { seed: 2, name: "Jaxon Joy", school: "Cornell" },
    { seed: 3, name: "Cross Wasilewski", school: "Penn" },
    { seed: 4, name: "Collin Gaj", school: "Virginia Tech" },
    { seed: 5, name: "Koy Buesgens", school: "NC State" },
    { seed: 6, name: "Caleb Tyus", school: "Southern Illinois" },
    { seed: 7, name: "Ethan Stiles", school: "Ohio State" },
    { seed: 8, name: "Casey Swiderski", school: "Oklahoma State" },
    { seed: 9, name: "David Evans", school: "Utah Valley" },
    { seed: 10, name: "Aden Valencia", school: "Stanford" },
    { seed: 11, name: "Lachlan McNeil", school: "Michigan" },
    { seed: 12, name: "Carter Young", school: "Maryland" },
    { seed: 13, name: "Joseph Zargo", school: "Wisconsin" },
    { seed: 14, name: "Caleb Rathjen", school: "Northern Iowa" },
    { seed: 15, name: "Ryder Block", school: "Iowa" },
    { seed: 16, name: "Jacob Frost", school: "Iowa State" },
    { seed: 17, name: "Lucas Kaputsta", school: "Lock Haven" },
    { seed: 18, name: "Eugene Harney", school: "Morgan State" },
    { seed: 19, name: "Brock Herman", school: "Little Rock" },
    { seed: 20, name: "Chance Lamer", school: "Nebraska" },
    { seed: 21, name: "Gabe Willochell", school: "Wyoming" },
    { seed: 22, name: "Eligh Rivera", school: "Princeton" },
    { seed: 23, name: "Max Peterson", school: "North Dakota State" },
    { seed: 24, name: "Andrew Clark", school: "Rutgers" },
    { seed: 25, name: "Michael Gioffre", school: "Illinois" },
    { seed: 26, name: "Anderson Heap", school: "Davidson" },
    { seed: 27, name: "Andre Gonzales", school: "Cal Poly" },
    { seed: 28, name: "Kade Brown", school: "Pittsburgh" },
    { seed: 29, name: "Kaden Cassidy", school: "George Mason" },
    { seed: 30, name: "Dylan Layton", school: "Rider" },
    { seed: 31, name: "Ryan Michaels", school: "Edinboro" },
    { seed: 32, name: "Clayton Jones", school: "Michigan State" },
    { seed: 33, name: "Austin McBurney", school: "Brown" },
  ],
  157: [
    { seed: 1, name: "PJ Duke", school: "Penn State" },
    { seed: 2, name: "Antrell Taylor", school: "Nebraska" },
    { seed: 3, name: "Meyer Shapiro", school: "Cornell" },
    { seed: 4, name: "Kaleb Larkin", school: "Arizona State" },
    { seed: 5, name: "Landon Robideau", school: "Oklahoma State" },
    { seed: 6, name: "Jude Swisher", school: "Penn" },
    { seed: 7, name: "Kannon Webster", school: "Illinois" },
    { seed: 8, name: "Brandon Cannon", school: "Ohio State" },
    { seed: 9, name: "Daniel Cardenas", school: "Stanford" },
    { seed: 10, name: "Logan Rozynski", school: "Lehigh" },
    { seed: 11, name: "Ty Watters", school: "West Virginia" },
    { seed: 12, name: "Vinny Zerban", school: "Iowa State" },
    { seed: 13, name: "Derek Raike", school: "Ohio" },
    { seed: 14, name: "Ethen Miller", school: "Virginia Tech" },
    { seed: 15, name: "Cameron Catrabone", school: "Michigan" },
    { seed: 16, name: "Cael Swensen", school: "South Dakota State" },
    { seed: 17, name: "Luke Mechler", school: "Wisconsin" },
    { seed: 18, name: "DJ McGee", school: "George Mason" },
    { seed: 19, name: "Kai Owen", school: "Columbia" },
    { seed: 20, name: "Jimmy Harrington", school: "Harvard" },
    { seed: 21, name: "Charlie Millard", school: "Minnesota" },
    { seed: 22, name: "Colton Washleski", school: "Virginia" },
    { seed: 23, name: "Kaleb Burgess", school: "Buffalo" },
    { seed: 24, name: "Jaivon Jones", school: "Little Rock" },
    { seed: 25, name: "Mason Shrader", school: "Central Michigan" },
    { seed: 26, name: "Johnathan Ley", school: "Navy" },
    { seed: 27, name: "Dylan Evans", school: "Pittsburgh" },
    { seed: 28, name: "Gavin Drexler", school: "North Dakota State" },
    { seed: 29, name: "Bryce Lowery", school: "Indiana" },
    { seed: 30, name: "Laird Root", school: "North Carolina" },
    { seed: 31, name: "Garrett McChesney", school: "Edinboro" },
    { seed: 32, name: "Jeb Prectel", school: "Bellarmine" },
    { seed: 33, name: "Yannis Charles", school: "Morgan State" },
  ],
  165: [
    { seed: 1, name: "Mitchell Messenbrink", school: "Penn State" },
    { seed: 2, name: "Joey Blaze", school: "Purdue" },
    { seed: 3, name: "Mike Caliendo", school: "Iowa" },
    { seed: 4, name: "Nicco Ruiz", school: "Arizona State" },
    { seed: 5, name: "LaDarion Lockett", school: "Oklahoma State" },
    { seed: 6, name: "LJ Araujo", school: "Nebraska" },
    { seed: 7, name: "Masx Brignola", school: "Lehigh" },
    { seed: 8, name: "Matty Bianchi", school: "Little Rock" },
    { seed: 9, name: "Bryce Hepner", school: "North Carolina" },
    { seed: 10, name: "Will Denny", school: "NC State" },
    { seed: 11, name: "Ryder Downey", school: "Northern Iowa" },
    { seed: 12, name: "Cesar Alvan", school: "Columbia" },
    { seed: 13, name: "Andrew Sparks", school: "Minnesota" },
    { seed: 14, name: "Andrew Barbosa", school: "Rutgers" },
    { seed: 15, name: "Connor Euton", school: "Iowa State" },
    { seed: 16, name: "Paddy Gallagher", school: "Ohio State" },
    { seed: 17, name: "Braeden Scoles", school: "Illinois" },
    { seed: 18, name: "Gunner Filipowicz", school: "Army" },
    { seed: 19, name: "Noah Mulvaney", school: "Bucknell" },
    { seed: 20, name: "Ty Whalen", school: "Princeton" },
    { seed: 21, name: "Brock Woodstock", school: "Southern Illinois" },
    { seed: 22, name: "Mathew Olguin", school: "Oregon State" },
    { seed: 23, name: "Chris Earnest", school: "Kent State" },
    { seed: 24, name: "Sean Seefeldt", school: "Penn" },
    { seed: 25, name: "Mac Church", school: "Virginia Tech" },
    { seed: 26, name: "Tyler Lillard", school: "Indiana" },
    { seed: 27, name: "EJ Parco", school: "Stanford" },
    { seed: 28, name: "Cody Goebel", school: "Wisconsin" },
    { seed: 29, name: "Ryan Burgos", school: "Edinboro" },
    { seed: 30, name: "Thomas Snipes", school: "Citadel" },
    { seed: 31, name: "Jared Keslar", school: "Pittsburgh" },
    { seed: 32, name: "Cody Welsh", school: "Drexel" },
    { seed: 33, name: "Ryan Vigil", school: "VMI" },
  ],
  174: [
    { seed: 1, name: "Levi Haines", school: "Penn State" },
    { seed: 2, name: "Simon Ruiz", school: "Cornell" },
    { seed: 3, name: "Christopher Minto", school: "Nebraska" },
    { seed: 4, name: "Carson Kharchla", school: "Ohio State" },
    { seed: 5, name: "Patrick Kennedy", school: "Iowa" },
    { seed: 6, name: "Matty Singleton", school: "NC State" },
    { seed: 7, name: "Cam Steed", school: "Missouri" },
    { seed: 8, name: "Alex Facundo", school: "Oklahoma State" },
    { seed: 9, name: "Beau Mantanona", school: "Michigan" },
    { seed: 10, name: "Myles Takats", school: "Bucknell" },
    { seed: 11, name: "MJ Gaitan", school: "Iowa State" },
    { seed: 12, name: "Carter Schubert", school: "Oklahoma" },
    { seed: 13, name: "Carter Baer", school: "Binghamton" },
    { seed: 14, name: "Moses Espinoza-Owens", school: "South Dakota State" },
    { seed: 15, name: "Danny Wask", school: "Navy" },
    { seed: 16, name: "Nick Fine", school: "Columbia" },
    { seed: 17, name: "Jared Simma", school: "Northern Iowa" },
    { seed: 18, name: "Colin Kelly", school: "Illinois" },
    { seed: 19, name: "Logan Messer", school: "George Mason" },
    { seed: 20, name: "Daschle Lamer", school: "Oregon State" },
    { seed: 21, name: "Lenny Pinto", school: "Rutgers" },
    { seed: 22, name: "Brody Baumann", school: "Purdue" },
    { seed: 23, name: "Luca Augustine", school: "Pittsburgh" },
    { seed: 24, name: "Garrett Thompson", school: "Ohio" },
    { seed: 25, name: "Sergio Desiante", school: "Virginia Tech" },
    { seed: 26, name: "Derek Gilcher", school: "Indiana" },
    { seed: 27, name: "Collin Carrigan", school: "North Carolina" },
    { seed: 28, name: "Holden Garcia", school: "Princeton" },
    { seed: 29, name: "Avery Bassett", school: "Lock Haven" },
    { seed: 30, name: "Riley Davis", school: "Wyoming" },
    { seed: 31, name: "Cael Valencia", school: "Arizona State" },
    { seed: 32, name: "Luke Condon", school: "Wisconsin" },
    { seed: 33, name: "Grant O'Dell", school: "Bellarmine" },
  ],
  184: [
    { seed: 1, name: "Rocco Welsh", school: "Penn State" },
    { seed: 2, name: "Aeoden Sinclair", school: "Missouri" },
    { seed: 3, name: "Max McEnelly", school: "Minnesota" },
    { seed: 4, name: "James Conway", school: "Franklin & Marshall" },
    { seed: 5, name: "Brock Mantanona", school: "Michigan" },
    { seed: 6, name: "Eddie Meitenbach", school: "Wyoming" },
    { seed: 7, name: "Angelo Ferrari", school: "Iowa" },
    { seed: 8, name: "Silas Allred", school: "Nebraska" },
    { seed: 9, name: "Chris Moore", school: "Illinois" },
    { seed: 10, name: "Caleb Campos", school: "American" },
    { seed: 11, name: "Shane Cartegena-Walsh", school: "Rutgers" },
    { seed: 12, name: "Dylan Fishback", school: "Ohio State" },
    { seed: 13, name: "Isaac Dean", school: "Iowa State" },
    { seed: 14, name: "Jaden Bullock", school: "Virginia Tech" },
    { seed: 15, name: "Sal Perrine", school: "Ohio" },
    { seed: 16, name: "Rylan Rogers", school: "Lehigh" },
    { seed: 17, name: "Ian Bush", school: "West Virginia" },
    { seed: 18, name: "Jake Dailey", school: "North Carolina" },
    { seed: 19, name: "Jared McGill", school: "Edinboro" },
    { seed: 20, name: "Brian Soldano", school: "Oklahoma" },
    { seed: 21, name: "Tomas Brooker", school: "Appalachian State" },
    { seed: 22, name: "Zach Ryder", school: "Oklahoma State" },
    { seed: 23, name: "Ceasar Garza", school: "Cal Poly" },
    { seed: 24, name: "Joe Curtis", school: "Columbia" },
    { seed: 25, name: "Malachi DuVall", school: "George Mason" },
    { seed: 26, name: "Chase Kranitz", school: "Pittsburgh" },
    { seed: 27, name: "Aidan Brenot", school: "North Dakota State" },
    { seed: 28, name: "Abraham Wojcikiewicz", school: "Stanford" },
    { seed: 29, name: "Nick Fox", school: "Northern Iowa" },
    { seed: 30, name: "Tyler Bienus", school: "Bucknell" },
    { seed: 31, name: "Mahonri Rushton", school: "Northern Colorado" },
    { seed: 32, name: "Caleb Uhlenhopp", school: "Utah Valley" },
    { seed: 33, name: "Sam Goin", school: "Indiana" },
  ],
  197: [
    { seed: 1, name: "Josh Barr", school: "Penn State" },
    { seed: 2, name: "Rocky Elam", school: "Iowa State" },
    { seed: 3, name: "Stephen Little", school: "Little Rock" },
    { seed: 4, name: "Sonny Sasso", school: "Virginia Tech" },
    { seed: 5, name: "Joey Novak", school: "Wyoming" },
    { seed: 6, name: "Justin Rademacher", school: "Oregon State" },
    { seed: 7, name: "Cody Merrill", school: "Oklahoma State" },
    { seed: 8, name: "DJ Parker", school: "Oklahoma" },
    { seed: 9, name: "Angelo Posada", school: "Stanford" },
    { seed: 10, name: "Mac Stout", school: "Pittsburgh" },
    { seed: 11, name: "Camden McDanel", school: "Nebraska" },
    { seed: 12, name: "Luke Geog", school: "Ohio State" },
    { seed: 13, name: "Bennett Berge", school: "South Dakota State" },
    { seed: 14, name: "Gabe Sollars", school: "Indiana" },
    { seed: 15, name: "Remy Cotton", school: "Rutgers" },
    { seed: 16, name: "Branson John", school: "Maryland" },
    { seed: 17, name: "Dillon Bechtold", school: "Bucknell" },
    { seed: 18, name: "Andrew Reall", school: "Brown" },
    { seed: 19, name: "Zayne Lehman", school: "Ohio" },
    { seed: 20, name: "Wyatt Ingham", school: "Wisconsin" },
    { seed: 21, name: "Rune Lawrence", school: "West Virginia" },
    { seed: 22, name: "Devin Wasley", school: "North Dakota State" },
    { seed: 23, name: "Mikey Squires", school: "Binghamton" },
    { seed: 24, name: "Brock Zurawski", school: "Rider" },
    { seed: 25, name: "Evan Bates", school: "Missouri" },
    { seed: 26, name: "Ben Vanadia", school: "Purdue" },
    { seed: 27, name: "Gabe Arnold", school: "Iowa" },
    { seed: 28, name: "Kael Wisler", school: "Michigan State" },
    { seed: 29, name: "Colton Hawks", school: "Arizona State" },
    { seed: 30, name: "Kade Rule", school: "Chattanooga" },
    { seed: 31, name: "Kael Bennie", school: "Utah Valley" },
    { seed: 32, name: "Blake Schaffer", school: "Kent State" },
    { seed: 33, name: "Karson Tompkins", school: "Air Force" },
  ],
  285: [
    { seed: 1, name: "Yonger Bastida", school: "Iowa State" },
    { seed: 2, name: "Isaac Trumble", school: "NC State" },
    { seed: 3, name: "Taye Ghadiali", school: "Michigan" },
    { seed: 4, name: "AJ Ferrari", school: "Nebraska" },
    { seed: 5, name: "Nick Feldman", school: "Ohio State" },
    { seed: 6, name: "Nathan Taylor", school: "Lehigh" },
    { seed: 7, name: "Konner Doucet", school: "Oklahoma State" },
    { seed: 8, name: "Ben Kueter", school: "Iowa" },
    { seed: 9, name: "Cole Mirasola", school: "Penn State" },
    { seed: 10, name: "David Szuba", school: "Arizona State" },
    { seed: 11, name: "Devon Dawson", school: "Northern Illinois" },
    { seed: 12, name: "Braxton Amos", school: "Wisconsin" },
    { seed: 13, name: "Spencer Lanosga", school: "Navy" },
    { seed: 14, name: "Koy Hopke", school: "Minnesota" },
    { seed: 15, name: "Brady Colbert", school: "Army" },
    { seed: 16, name: "Jimmy Mullen", school: "Virginia Tech" },
    { seed: 17, name: "Vincent Mueller", school: "Columbia" },
    { seed: 18, name: "Christian Carroll", school: "Wyoming" },
    { seed: 19, name: "Nate Schon", school: "Drexel" },
    { seed: 20, name: "Dayton Pitzer", school: "Pittsburgh" },
    { seed: 21, name: "Juan Mora", school: "Oklahoma" },
    { seed: 22, name: "Trevor Tinker", school: "Cal Poly" },
    { seed: 23, name: "Stephan Monochery", school: "Appalachian State" },
    { seed: 24, name: "Connor Barket", school: "Duke" },
    { seed: 25, name: "Alex Semenenko", school: "Brown" },
    { seed: 26, name: "Luke Luffman", school: "Illinois" },
    { seed: 27, name: "Hunter Catka", school: "Rutgers" },
    { seed: 28, name: "Jarrett Stoner", school: "Missouri" },
    { seed: 29, name: "Luke Rasmussen", school: "South Dakota State" },
    { seed: 30, name: "Jack Forbes", school: "Utah Valley" },
    { seed: 31, name: "Brenen Morgan", school: "Virginia" },
    { seed: 32, name: "Emmanuel Ulrich", school: "American" },
    { seed: 33, name: "Mason Rebuck", school: "Bloomsburg" },
  ],
};

export const PLACEMENT_POINTS = { 1: 16, 2: 12, 3: 10, 4: 9, 5: 7, 6: 6, 7: 4, 8: 3 };

export const SCHOOL_COLORS = {
  "Air Force": "#00308F",
  "American": "#CC0000",
  "Appalachian State": "#222222",
  "Arizona State": "#8C1D40",
  "Army": "#1F3764",
  "Bellarmine": "#CC0000",
  "Binghamton": "#005A43",
  "Bloomsburg": "#C41230",
  "Brown": "#4E3629",
  "Bucknell": "#E87722",
  "Buffalo": "#005BBB",
  "Cal Poly": "#1F4F2E",
  "Central Michigan": "#6A0032",
  "Chattanooga": "#00386B",
  "Citadel": "#003C71",
  "Clarion": "#003087",
  "Columbia": "#69B3E7",
  "Cornell": "#B31B1B",
  "Davidson": "#CC0000",
  "Drexel": "#07294D",
  "Duke": "#003087",
  "Edinboro": "#CC0000",
  "Franklin & Marshall": "#002868",
  "Gardner Webb": "#BF0D3E",
  "George Mason": "#006633",
  "Harvard": "#A51C30",
  "Illinois": "#E84A27",
  "Indiana": "#990000",
  "Iowa": "#FFCD00",
  "Iowa State": "#C8102E",
  "Kent State": "#002664",
  "Lehigh": "#652B16",
  "Little Rock": "#75003B",
  "Lock Haven": "#7E1032",
  "Maryland": "#E03A3E",
  "Michigan": "#FFCB05",
  "Michigan State": "#18453B",
  "Minnesota": "#7A0019",
  "Missouri": "#F1B82D",
  "Morgan State": "#EF6F20",
  "NC State": "#CC0000",
  "Navy": "#00205B",
  "Nebraska": "#E41C38",
  "North Carolina": "#7BAFD4",
  "North Dakota State": "#006A31",
  "Northern Colorado": "#003366",
  "Northern Illinois": "#BA0C2F",
  "Northern Iowa": "#4B116F",
  "Northwestern": "#4E2A84",
  "Ohio": "#00694E",
  "Ohio State": "#BB0000",
  "Oklahoma": "#841617",
  "Oklahoma State": "#FF7300",
  "Oregon State": "#D73F09",
  "Penn": "#011F5B",
  "Penn State": "#1E407C",
  "Pittsburgh": "#003594",
  "Princeton": "#E77500",
  "Purdue": "#CEB888",
  "Rider": "#602040",
  "Rutgers": "#CC0033",
  "South Dakota State": "#00539B",
  "Southern Illinois": "#720000",
  "Stanford": "#8C1515",
  "Utah Valley": "#275D38",
  "VMI": "#CC0000",
  "Virginia": "#232D4B",
  "Virginia Tech": "#75162F",
  "West Virginia": "#002855",
  "Wisconsin": "#C5050C",
  "Wyoming": "#492F24",
};

export const getSchoolColor = (school) => SCHOOL_COLORS[school] || "#666";

export const SEED_ENTRIES = [
  { id: 1742000000001, name: "AJ Buckiso", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000002, name: "Andy Clark", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000003, name: "Annese Bayless", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:1,name:"Jax Forrest",school:"Oklahoma State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:10,name:"Caleb Campos",school:"American"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:6,name:"Nathan Taylor",school:"Lehigh"} } },
  { id: 1742000000004, name: "Asher Rose", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000005, name: "Billy Westfall", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:1,name:"Shayne Van Ness",school:"Penn State"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:11,name:"Ryder Downey",school:"Northern Iowa"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:5,name:"Brock Mantanona",school:"Michigan"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000006, name: "Brent Rose", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:1,name:"Jax Forrest",school:"Oklahoma State"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000007, name: "Brian Westfall", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:3,name:"Taye Ghadiali",school:"Michigan"} } },
  { id: 1742000000008, name: "Brittany Yoho", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:1,name:"Levi Haines",school:"Penn State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:5,name:"Joey Novak",school:"Wyoming"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000009, name: "Casey Taylor", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:12,name:"Dylan Fishback",school:"Ohio State"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000010, name: "Chris Thomas", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:4,name:"Anthony Echemendia",school:"Iowa State"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:10,name:"Myles Takats",school:"Bucknell"}, 184:{seed:6,name:"Eddie Meitenbach",school:"Wyoming"}, 197:{seed:8,name:"DJ Parker",school:"Oklahoma"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000011, name: "Chris Thrasher", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:2,name:"Joey Blaze",school:"Purdue"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000012, name: "Christopher Thomas", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000013, name: "Cole Thomas", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:4,name:"Nicco Ruiz",school:"Arizona State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:5,name:"Brock Mantanona",school:"Michigan"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000014, name: "Dan Spencer", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:15,name:"Ryder Block",school:"Iowa"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000015, name: "Dave Klepfer", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:15,name:"Danny Wask",school:"Navy"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000016, name: "David Rose 1", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:6,name:"LJ Araujo",school:"Nebraska"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000017, name: "David Rose 2", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000018, name: "Derek Hillman", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:10,name:"David Szuba",school:"Arizona State"} } },
  { id: 1742000000019, name: "Emery Rose", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:6,name:"Nathan Taylor",school:"Lehigh"} } },
  { id: 1742000000020, name: "Eric Snyder", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:5,name:"Kyler Larkin",school:"Arizona State"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:1,name:"Levi Haines",school:"Penn State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000021, name: "Grant Parrish", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000022, name: "Griffin Taylor", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:12,name:"Dylan Fishback",school:"Ohio State"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000023, name: "Hunter Bresnan", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000024, name: "Jamar Henry", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000025, name: "James Walker", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:8,name:"DJ Parker",school:"Oklahoma"}, 285:{seed:10,name:"David Szuba",school:"Arizona State"} } },
  { id: 1742000000026, name: "Jared Leidich", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:6,name:"LJ Araujo",school:"Nebraska"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000027, name: "Jayden Walker", picks: { 125:{seed:10,name:"Marc-Anthony McGowan",school:"Princeton"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000028, name: "Jerry Kendall", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000029, name: "Jim Anglum", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000030, name: "Jim Kusar", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:4,name:"Carson Kharchla",school:"Ohio State"}, 184:{seed:6,name:"Eddie Meitenbach",school:"Wyoming"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000031, name: "Jimmy Blankenship", picks: { 125:{seed:2,name:"Eddie Ventresca",school:"Virginia Tech"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:8,name:"DJ Parker",school:"Oklahoma"}, 285:{seed:15,name:"Brady Colbert",school:"Army"} } },
  { id: 1742000000032, name: "Jimmy DeMore", picks: { 125:{seed:2,name:"Eddie Ventresca",school:"Virginia Tech"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000033, name: "Joe DeMore", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000034, name: "Joe Montalbano 1", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000035, name: "Joe Montalbano 2", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000036, name: "Joe Unger", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:4,name:"Anthony Echemendia",school:"Iowa State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:10,name:"Logan Rozynski",school:"Lehigh"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000037, name: "Jordan Victor", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:10,name:"Myles Takats",school:"Bucknell"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:7,name:"Konner Doucet",school:"Oklahoma State"} } },
  { id: 1742000000038, name: "Kevin Bateman 1", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:4,name:"Carson Kharchla",school:"Ohio State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000039, name: "Kevin Bateman 2", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:18,name:"Christian Carroll",school:"Wyoming"} } },
  { id: 1742000000040, name: "Kevin Bateman 3", picks: { 125:{seed:24,name:"Ayden Smith",school:"Rutgers"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000041, name: "Kevin McElhaney", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000042, name: "Kris Bishop", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000043, name: "Lane Popovitch", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:8,name:"Matty Bianchi",school:"Little Rock"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000044, name: "Lee Totten", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:6,name:"Jude Swisher",school:"Penn"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000045, name: "Mark Bateman 1", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000046, name: "Mark Bateman 2", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000047, name: "Mark Harrington", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000048, name: "Mark Hedlund Jr.", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:10,name:"Jack Consiglio",school:"Stanford"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000049, name: "Matt Herrick", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000050, name: "Matthew Harrington", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:3,name:"Taye Ghadiali",school:"Michigan"} } },
  { id: 1742000000051, name: "Michael Hills", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000052, name: "Owen Blankenship", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:3,name:"Taye Ghadiali",school:"Michigan"} } },
  { id: 1742000000053, name: "Owen Herrick", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000054, name: "Rick Ortz", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:5,name:"Joey Novak",school:"Wyoming"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000055, name: "Rob Whiteside", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:27,name:"Gabe Arnold",school:"Iowa"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000056, name: "Robert Elchynski", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:11,name:"CJ Composto",school:"Penn"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000057, name: "Ryan Hills", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:5,name:"LaDarion Lockett",school:"Oklahoma State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:12,name:"Luke Geog",school:"Ohio State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000058, name: "Samantha Rose", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:5,name:"Joey Novak",school:"Wyoming"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000059, name: "Sean Bayless", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000060, name: "Sean Connole", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000061, name: "Shelton Mack", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000062, name: "Stephen Maietta 1", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:7,name:"Kannon Webster",school:"Illinois"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:12,name:"Dylan Fishback",school:"Ohio State"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000063, name: "Stephen Maietta 2", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000064, name: "Steve Popovitch", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:13,name:"Wyatt Henson",school:"Lock Haven"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000065, name: "TJ Rodgers", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:6,name:"Caleb Tyus",school:"Southern Illinois"}, 157:{seed:10,name:"Logan Rozynski",school:"Lehigh"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000066, name: "Todd Victor", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:10,name:"Will Denny",school:"NC State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000067, name: "Wes Uhrin", picks: { 125:{seed:7,name:"Nico Provo",school:"Stanford"}, 133:{seed:5,name:"Kyler Larkin",school:"Arizona State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000068, name: "William Cunningham", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:12,name:"Carter Young",school:"Maryland"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000069, name: "Gabrielle Malinowski", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:6,name:"Eddie Meitenbach",school:"Wyoming"}, 197:{seed:4,name:"Sonny Sasso",school:"Virginia Tech"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000070, name: "Jonny Walker", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:9,name:"Dominick Serrano",school:"Northern Colorado"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000071, name: "Jeffrey Walker", picks: { 125:{seed:9,name:"Maximo Renteria",school:"Oregon State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:6,name:"Matty Singleton",school:"NC State"}, 184:{seed:4,name:"James Conway",school:"Franklin & Marshall"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:3,name:"Taye Ghadiali",school:"Michigan"} } },
  { id: 1742000000072, name: "Derek Nagy", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:2,name:"Jaxon Joy",school:"Cornell"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:8,name:"Matty Bianchi",school:"Little Rock"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000073, name: "Mike Snyder", picks: { 125:{seed:2,name:"Eddie Ventresca",school:"Virginia Tech"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000074, name: "Colin Nagy", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:6,name:"Nathan Taylor",school:"Lehigh"} } },
  { id: 1742000000075, name: "Stacy Klepfer", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:5,name:"Joey Novak",school:"Wyoming"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000076, name: "Blair Bateman 1", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:11,name:"Camden McDanel",school:"Nebraska"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000077, name: "Blair Bateman 2", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:22,name:"Zach Ryder",school:"Oklahoma State"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:5,name:"Nick Feldman",school:"Ohio State"} } },
  { id: 1742000000078, name: "Jordan Moss", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:1,name:"Jax Forrest",school:"Oklahoma State"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:4,name:"Collin Gaj",school:"Virginia Tech"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:9,name:"Bryce Hepner",school:"North Carolina"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000079, name: "Mark Katz", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:17,name:"Lucas Kaputsta",school:"Lock Haven"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:7,name:"Cody Merrill",school:"Oklahoma State"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000080, name: "Evan Holober", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:9,name:"Joey Olivieri",school:"Rutgers"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:6,name:"Jude Swisher",school:"Penn"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:12,name:"Carter Schubert",school:"Oklahoma"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000081, name: "Dan Volna", picks: { 125:{seed:12,name:"Vincent Robinson",school:"NC State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:8,name:"Vance Vombaur",school:"Minnesota"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:6,name:"Eddie Meitenbach",school:"Wyoming"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000082, name: "Jim Schoonover", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:1,name:"Jax Forrest",school:"Oklahoma State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:7,name:"Ethan Stiles",school:"Ohio State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:4,name:"Carson Kharchla",school:"Ohio State"}, 184:{seed:5,name:"Brock Mantanona",school:"Michigan"}, 197:{seed:8,name:"DJ Parker",school:"Oklahoma"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000083, name: "Erik Bestwick", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:6,name:"Drake Ayala",school:"Iowa"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:5,name:"Koy Buesgens",school:"NC State"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000084, name: "Jacob Ohl", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:4,name:"Collin Gaj",school:"Virginia Tech"}, 157:{seed:5,name:"Landon Robideau",school:"Oklahoma State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:8,name:"Silas Allred",school:"Nebraska"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000085, name: "Josh Walker", picks: { 125:{seed:8,name:"Dean Peterson",school:"Iowa"}, 133:{seed:1,name:"Jax Forrest",school:"Oklahoma State"}, 141:{seed:3,name:"Brock Hardy",school:"Nebraska"}, 149:{seed:20,name:"Chance Lamer",school:"Nebraska"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:6,name:"LJ Araujo",school:"Nebraska"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000086, name: "Bobby Tumpak", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:9,name:"Angelo Posada",school:"Stanford"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000087, name: "Jarred Walker", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:7,name:"Lucas Byrd",school:"Illinois"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:9,name:"David Evans",school:"Utah Valley"}, 157:{seed:4,name:"Kaleb Larkin",school:"Arizona State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:3,name:"Max McEnelly",school:"Minnesota"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:12,name:"Braxton Amos",school:"Wisconsin"} } },
  { id: 1742000000088, name: "Matt Zuckerman", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:10,name:"Aden Valencia",school:"Stanford"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:3,name:"Mike Caliendo",school:"Iowa"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:1,name:"Josh Barr",school:"Penn State"}, 285:{seed:2,name:"Isaac Trumble",school:"NC State"} } },
  { id: 1742000000089, name: "Nick Montalbano", picks: { 125:{seed:6,name:"Jore Volk",school:"Minnesota"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:11,name:"Ty Watters",school:"West Virginia"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:5,name:"Patrick Kennedy",school:"Iowa"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:3,name:"Stephen Little",school:"Little Rock"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000090, name: "Jon Connole", picks: { 125:{seed:4,name:"Sheldon Seymour",school:"Lehigh"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:20,name:"Jimmy Harrington",school:"Harvard"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:7,name:"Cam Steed",school:"Missouri"}, 184:{seed:2,name:"Aeoden Sinclair",school:"Missouri"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000091, name: "George Chase", picks: { 125:{seed:3,name:"Nic Bouzakis",school:"Ohio State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:5,name:"Luke Stanich",school:"Lehigh"}, 149:{seed:15,name:"Ryder Block",school:"Iowa"}, 157:{seed:2,name:"Antrell Taylor",school:"Nebraska"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:8,name:"Alex Facundo",school:"Oklahoma State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:6,name:"Justin Rademacher",school:"Oregon State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000092, name: "Brady Watkins", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:11,name:"Lachlan McNeil",school:"Michigan"}, 157:{seed:8,name:"Brandon Cannon",school:"Ohio State"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:4,name:"Carson Kharchla",school:"Ohio State"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000093, name: "Hudson Watkins", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:2,name:"Sergio Vega",school:"Oklahoma State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:6,name:"Jude Swisher",school:"Penn"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:3,name:"Christopher Minto",school:"Nebraska"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:27,name:"Gabe Arnold",school:"Iowa"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
  { id: 1742000000094, name: "Jason Waelti", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:3,name:"Marcus Blaze",school:"Penn State"}, 141:{seed:4,name:"Anthony Echemendia",school:"Iowa State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:9,name:"Daniel Cardenas",school:"Stanford"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:10,name:"Myles Takats",school:"Bucknell"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:6,name:"Nathan Taylor",school:"Lehigh"} } },
  { id: 1742000000095, name: "Dave Kruszewski", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:2,name:"Ben Davino",school:"Ohio State"}, 141:{seed:1,name:"Jesse Mendez",school:"Ohio State"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:6,name:"LJ Araujo",school:"Nebraska"}, 174:{seed:9,name:"Beau Mantanona",school:"Michigan"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:10,name:"Mac Stout",school:"Pittsburgh"}, 285:{seed:4,name:"AJ Ferrari",school:"Nebraska"} } },
  { id: 1742000000096, name: "Ken Watkins", picks: { 125:{seed:5,name:"Troy Spratley",school:"Oklahoma State"}, 133:{seed:4,name:"Aaron Seidel",school:"Virginia Tech"}, 141:{seed:6,name:"Vince Cornella",school:"Cornell"}, 149:{seed:8,name:"Casey Swiderski",school:"Oklahoma State"}, 157:{seed:3,name:"Meyer Shapiro",school:"Cornell"}, 165:{seed:1,name:"Mitchell Messenbrink",school:"Penn State"}, 174:{seed:15,name:"Danny Wask",school:"Navy"}, 184:{seed:7,name:"Angelo Ferrari",school:"Iowa"}, 197:{seed:2,name:"Rocky Elam",school:"Iowa State"}, 285:{seed:9,name:"Cole Mirasola",school:"Penn State"} } },
];
